const { test, expect } = require('@playwright/test');
const { suppressBackupModalForFunctionalTest } = require('./test-helper.cjs');

for (const owner of ['NSA', 'EVT']) test(`${owner}: nomination is staged, validated, saved and restored`, async ({ page }) => {
  await suppressBackupModalForFunctionalTest(page);
  await page.goto(`/src/program-planner/${owner === 'NSA' ? 'nsa' : 'events'}.html`);
  let frame = page.frames().find(f => f !== page.mainFrame());
  await frame.waitForFunction(() => window.UOS?.ProgramApp?.snapshot().phase === 'ready');
  const ids = await frame.evaluate(async owner => {
    const UOS = window.UOS;
    let ids;
    await UOS.ProgramApp.updateWorkspace(ws => {
      const id = owner === 'NSA' ? 'NSA-APP-NOMINATION' : 'EVT-EVENT-NOMINATION';
      ws.entities[owner === 'NSA' ? 'applications' : 'events'].push({ id, owner, type: owner === 'NSA' ? 'application' : 'event', title: 'Nomination browser test', status: 'received', dateReceived: '2026-10-02' });
      const promoted = UOS.ProgramModel.promoteRegisterRecord(ws, id);
      const canonical = UOS.ProgramStatus.migrate(promoted.workspace);
      const saved = UOS.ProgramPlannerModel.saveTask(canonical, promoted.project.id, null, { title: 'Main works', description: 'Deliver main works', section: 'Planning and Approval', operational: true, status: 'Not Started' });
      const draft = UOS.ProgramPlannerModel.createDraftJob(saved.workspace, promoted.project.id, saved.task.id);
      draft.workspace.statusControl.automationEnabled = true;
      ids = { jobId: draft.job.id, registerId: id };
      return draft.workspace;
    });
    await UOS.ProgramApp.navigateWithContext('scheduler', ids.jobId);
    await UOS.ProgramSchedulerUI.focusCalendarJob(ids.jobId);
    return ids;
  }, owner);
  const form = () => frame.locator('[data-scheduler-form]');
  const nomination = () => form().getByRole('checkbox', { name: 'Updates application status for the main works' });
  const savedJob = () => frame.evaluate(id => window.UOS.ProgramApp.workspace().entities.jobs.find(j => j.id === id), ids.jobId);
  const applicationStatus = () => frame.evaluate(id => [...window.UOS.ProgramApp.workspace().entities.applications, ...window.UOS.ProgramApp.workspace().entities.events].find(r => r.id === id).status, ids.registerId);
  await expect(nomination()).not.toBeChecked();
  await expect(frame.locator('#scheduler-application-status-help')).toHaveText('When scheduled, this job can mark the application Scheduled. For Nature Strip works, starting this job can also mark the application In Progress.');
  await expect(form().getByRole('button', { name: 'Job status', exact: true })).toBeVisible();
  await expect(form().getByRole('button', { name: 'Delete job', exact: true })).toBeVisible();
  await nomination().check();
  expect((await savedJob()).updatesApplicationStatus).toBe(false);
  await frame.evaluate(async id => {
    await window.UOS.ProgramApp.navigateWithContext('costing', id);
    await window.UOS.ProgramApp.navigateWithContext('scheduler', id);
    await window.UOS.ProgramSchedulerUI.focusCalendarJob(id);
  }, ids.jobId);
  await expect(nomination()).not.toBeChecked();
  await form().locator('[name="allDay"]').check();
  await form().locator('[name="startDate"]').fill('2026-10-05');
  await form().getByRole('button', { name: 'Save schedule', exact: true }).click();
  await expect.poll(async () => (await savedJob()).status).toBe('scheduled');
  expect(await applicationStatus()).toBe('received');
  await nomination().check();
  await form().locator('[name="sameDay"]').uncheck();
  await form().locator('[name="endDate"]').fill('2026-10-04');
  await form().getByRole('button', { name: 'Save schedule', exact: true }).click();
  await expect(form().locator('[data-scheduler-form-error]')).toBeVisible();
  expect((await savedJob()).updatesApplicationStatus).toBe(false);
  expect(await applicationStatus()).toBe('received');
  await form().locator('[name="endDate"]').fill('2026-10-05');
  await form().getByRole('button', { name: 'Save schedule', exact: true }).click();
  await expect.poll(async () => (await savedJob()).updatesApplicationStatus).toBe(true);
  await expect.poll(applicationStatus).toBe('scheduled');
  await expect(frame.locator('[data-program-persistence]')).toHaveText('Saved');
  await page.reload();
  frame = page.frames().find(f => f !== page.mainFrame());
  await frame.waitForFunction(() => window.UOS?.ProgramApp?.snapshot().phase === 'ready');
  await frame.evaluate(async id => {
    await window.UOS.ProgramApp.navigateWithContext('scheduler', id);
    await window.UOS.ProgramSchedulerUI.focusCalendarJob(id);
  }, ids.jobId);
  await expect(nomination()).toBeChecked();
  expect(await applicationStatus()).toBe('scheduled');
  await nomination().uncheck();
  await form().getByRole('button', { name: 'Save schedule', exact: true }).click();
  await expect.poll(async () => (await savedJob()).updatesApplicationStatus).toBe(false);
  expect(await applicationStatus()).toBe('scheduled');
  await form().getByRole('button', { name: 'Job status', exact: true }).click();
  const dialog = frame.locator('[data-status-lifecycle-dialog]');
  await expect(dialog).toBeVisible();
  await expect(dialog.locator('[data-status-pause]')).toBeVisible();
  await expect(dialog.locator('[data-status-command="in_progress"]')).toBeVisible();
  await expect(dialog.locator('.program-status-events')).toBeVisible();
});
