'use strict';
const assert=require('assert');
const path=require('path');
const root=process.argv[2]||path.resolve(__dirname,'../review56_pr25');
const f=(s)=>require(path.join(root,s));
global.window=global;
f('js/utils/absences.js');
f('js/utils/qualifications.js');
f('js/utils/fatigueEngine.js');
f('js/utils/eligibilityEngine.js');
f('js/components/staffAssignModal/candidateModel.js');
f('js/app.js');
const app=global.HortOpsApp;
const record={id:'A1', staffId:'A', type:'annual_leave',startDate:'2026-10-10',endDate:'2026-10-11'};
const refusal={id:'R1',staffId:'B',shiftId:'X',date:'2026-08-01'};
const roster=[{id:'A',name:'Alan',status:'active',team:'Parks',department:'Horticulture',role:'Worker',ytdOvertimeHours:12},{id:'B',name:'Beth',status:'active',team:'Parks',department:'Horticulture',role:'Worker',ytdOvertimeHours:12}];
let saved=null;
const workspace={jobs:[],roster,assignments:{},rostering:{instructions:{},provenance:{}},historicalSnapshots:{},permits:{},budgetSettings:{},uiState:{},absences:[record],refusalHistory:[refusal]};
global.HortOpsScheduler={DEFAULT_BUDGET_SETTINGS:{}};
global.HortOpsStorage={loadWorkspace:()=>workspace,readVerifiedCommittedV2:()=>({ok:true,exists:false}),createWorkspaceEnvelope:x=>x,saveWorkspace:x=>{saved=x;return {ok:true}}};
global.HortOpsSchemaValidator={validateCurrentV2Presence:()=>({valid:true})};
app.recomputeDigest=function(){};app.renderCurrentView=function(){};
app.init();
assert(!Object.hasOwn(app.state,'absences'), 'Expected to reproduce dropped absences on initialization');
assert(!Object.hasOwn(app.state,'refusalHistory'), 'Expected dropped refusal history on initialization');
console.log('R56-P01 REPRODUCED: init() drops populated absence/refusal domains from valid loaded workspace');
const shift={shiftId:'SHIFT1',date:'2026-10-10',startTime:'07:00',durationHours:5,assignedStaffIds:[]};
let absent=global.HortOpsEligibilityEngine.validateStaffEligibility(roster[0],shift,{},[],[]);
assert.strictEqual(absent.eligible,true);
console.log('R56-P01b REPRODUCED: unloaded absence ledger permits on-leave worker in normal runtime');
app.state.absences=[record];app.state.refusalHistory=[refusal];
const result=app._commitCanonicalProposal({});
assert.strictEqual(result.success,true);
assert(!Object.hasOwn(saved,'absences') && !Object.hasOwn(saved,'refusalHistory'));
console.log('R56-P02 REPRODUCED: normal successful commit silently omits both populated live domains');
const cm=global.HortOpsStaffAssignCandidateModel;
const cand=roster.map(s=>({...s,_fatigueEval:{tier:'LOW',consecutiveWeekends:0},_lacksQualifications:false}));
const sorted=cm.sortCandidates(cand,{matchingJob:{},prefs:{},assignedIdsSet:new Set()});
assert.deepStrictEqual(sorted.map(x=>x.id),['A','B']);
assert(global.HortOpsAbsences.calculateFairShareScore(roster[1],{refusalCount:1})>global.HortOpsAbsences.calculateFairShareScore(roster[0],{refusalCount:0}));
console.log('R56-P03 REPRODUCED: candidate ranking A before B despite B fair-share score exceeding A');
const oldFatigue=global.HortOpsFatigueEngine;
global.HortOpsFatigueEngine={};
const noFatigue=global.HortOpsEligibilityEngine.validateStaffEligibility(roster[0],{...shift,date:'2026-10-17'}, {}, [], []);
assert.strictEqual(noFatigue.eligible,true);
console.log('R56-P04 REPRODUCED: missing fatigue method silently permits allocation');
global.HortOpsFatigueEngine=oldFatigue;
const oldAbs=global.HortOpsAbsences, oldLedger=global.HortOpsAbsenceLedger;
global.HortOpsAbsences={}; global.HortOpsAbsenceLedger=null;
const noAbs=global.HortOpsEligibilityEngine.validateStaffEligibility(roster[0],shift,{},[],[],{absences:[record]});
assert.strictEqual(noAbs.eligible,true);
console.log('R56-P05 REPRODUCED: absent worker becomes eligible when absence engine method unavailable');
global.HortOpsAbsences=oldAbs;global.HortOpsAbsenceLedger=oldLedger;
console.log('SUMMARY: 5 independently reproduced departures (including separate eligibility consequence P01b).');
