/* GeoForge: client-side spatial file conversion and MapLibre drawing. */
'use strict';
(()=>{
const $=id=>document.getElementById(id), R=6371008.8;
const state={items:[],nextId:1,selected:null,mode:'select',vertices:[],cursor:null,markers:[],map:null,metroReady:false,metroTemplate:null,lastFocus:null};
const BLANK={type:'FeatureCollection',features:[]};
const style={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'},features:{type:'geojson',data:BLANK},drawing:{type:'geojson',data:BLANK}},layers:[{id:'osm',type:'raster',source:'osm'},{id:'polygons',type:'fill',source:'features',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':'#49d9ac','fill-opacity':.19}},{id:'polygon-outline',type:'line',source:'features',filter:['==',['geometry-type'],'Polygon'],paint:{'line-color':'#41e2a9','line-width':2.5}},{id:'lines',type:'line',source:'features',filter:['==',['geometry-type'],'LineString'],paint:{'line-color':'#21e8ff','line-width':3}},{id:'points',type:'circle',source:'features',filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':6,'circle-color':'#fbd36a','circle-stroke-width':2,'circle-stroke-color':'#173c42'}},{id:'selected-line',type:'line',source:'features',filter:['==',['get','_fid'],-1],paint:{'line-color':'#fff','line-width':5,'line-opacity':.7}},{id:'selected-points',type:'circle',source:'features',filter:['==',['get','_fid'],-1],paint:{'circle-radius':10,'circle-color':'#fff','circle-opacity':.25,'circle-stroke-width':2,'circle-stroke-color':'#fff'}},{id:'draw-fill',type:'fill',source:'drawing',paint:{'fill-color':'#f8de6e','fill-opacity':.16}},{id:'draw-lines',type:'line',source:'drawing',paint:{'line-color':'#ffe07c','line-width':3,'line-dasharray':[2,1]}},{id:'draw-points',type:'circle',source:'drawing',paint:{'circle-radius':5,'circle-color':'#ffdf76','circle-stroke-color':'#2b3b3b','circle-stroke-width':1}}]};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4500)}
function notice(message){$('map-notice').textContent=message;$('map-notice').classList.remove('hidden');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('map-notice').classList.add('hidden'),9000)}
function escapeXML(s){return String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]))}
function cleanProperties(p){const out={};for(const [k,v] of Object.entries(p||{})){if(k==='_fid'||k==='_source')continue;out[k]=v}return out}
function geofeature(item){return {type:'Feature',geometry:structuredClone(item.feature.geometry),properties:cleanProperties(item.feature.properties)}}
function visible(){return state.items.filter(x=>x.visible)}
function scoped(){let rows=$('export-scope').value==='visible'?visible():$('export-scope').value==='selected'?state.items.filter(x=>x.id===state.selected):state.items;return rows.map(geofeature)}
function normalizeGeometry(geom){if(!geom||!geom.type)return [];if(geom.type==='GeometryCollection')return(geom.geometries||[]).flatMap(normalizeGeometry);if(!['Point','MultiPoint','LineString','MultiLineString','Polygon','MultiPolygon'].includes(geom.type))return [];return [geom]}
function addFeatures(features,source){let n=0;for(const f of features){if(!f||!f.geometry)continue;for(const geom of normalizeGeometry(f.geometry)){if(!validGeometry(geom))continue;const id=state.nextId++;const props=Object.assign({},f.properties||{});state.items.push({id,source,visible:true,feature:{type:'Feature',geometry:geom,properties:props}});n++}}refresh();return n}
function validGeometry(geom){const walk=c=>typeof c[0]==='number'?c.length>=2&&Number.isFinite(c[0])&&Number.isFinite(c[1]):Array.isArray(c)&&c.every(walk);return Array.isArray(geom.coordinates)&&walk(geom.coordinates)}
function renderGeometry(){return {type:'FeatureCollection',features:visible().map(x=>({type:'Feature',geometry:x.feature.geometry,properties:{...x.feature.properties,_fid:x.id}}))}}
function refresh(){if(state.map?.getSource('features'))state.map.getSource('features').setData(renderGeometry());for(const id of ['selected-line','selected-points'])if(state.map?.getLayer(id))state.map.setFilter(id,['==',['get','_fid'],state.selected??-1]);const total=state.items.length;$('feature-count').textContent=`${total} feature${total===1?'':'s'}`;$('delete-selected').disabled=state.selected===null;renderList();renderStats();renderLabels()}
function geometryKind(g){return g.type.includes('Polygon')?'polygon':g.type.includes('LineString')?'line':'point'}
function renderList(){const root=$('layers-list');root.innerHTML='';if(!state.items.length){root.innerHTML='<div class="empty-state">No geometry loaded. Import a file or draw on the map.</div>';return}for(const item of state.items){const kind=geometryKind(item.feature.geometry);const row=document.createElement('div');row.className='layer-row'+(item.id===state.selected?' selected':'');row.title='Click to select; double-click to zoom';const symbol=document.createElement('span');symbol.className='geometry-marker';symbol.textContent=kind==='polygon'?'⬡':kind==='line'?'⌁':'⊙';const txt=document.createElement('div');txt.className='layer-text';const name=document.createElement('div');name.className='layer-title';name.textContent=item.feature.properties?.name||`${kind[0].toUpperCase()+kind.slice(1)} ${item.id}`;const sub=document.createElement('small');sub.textContent=item.source;txt.append(name,sub);const eye=document.createElement('button');eye.className='visibility'+(item.visible?'':' off');eye.textContent=item.visible?'◉':'○';eye.title=item.visible?'Hide feature':'Show feature';eye.onclick=e=>{e.stopPropagation();item.visible=!item.visible;refresh()};row.append(symbol,txt,eye);row.onclick=()=>{state.selected=item.id;refresh()};row.ondblclick=()=>fitFeatures([item]);root.append(row)}}
function renderStats(){let p=0,l=0,a=0;for(const x of state.items){const t=geometryKind(x.feature.geometry);if(t==='point')p++;else if(t==='line')l++;else a++}$('stat-points').textContent=p;$('stat-lines').textContent=l;$('stat-polygons').textContent=a}
function eachPosition(node,fn){if(!Array.isArray(node))return;if(typeof node[0]==='number'){fn(node);return}for(const c of node)eachPosition(c,fn)}
function fitFeatures(rows=visible()){const coords=[];for(const row of rows)eachPosition(row.feature.geometry.coordinates,c=>coords.push(c));if(!coords.length){toast('Nothing to zoom to');return}if(coords.length===1){state.map.flyTo({center:coords[0].slice(0,2),zoom:17});return}let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(const c of coords){minx=Math.min(minx,c[0]);miny=Math.min(miny,c[1]);maxx=Math.max(maxx,c[0]);maxy=Math.max(maxy,c[1])}state.map.fitBounds([[minx,miny],[maxx,maxy]],{padding:80,maxZoom:18,duration:650})}
const rad=d=>d*Math.PI/180;function distance(a,b){const dlat=rad(b[1]-a[1]),dlng=rad(b[0]-a[0]);const x=Math.sin(dlat/2)**2+Math.cos(rad(a[1]))*Math.cos(rad(b[1]))*Math.sin(dlng/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(x)))}
function lineLength(coords){let v=0;for(let i=1;i<coords.length;i++)v+=distance(coords[i-1],coords[i]);return v}
function ringArea(ring){if(ring.length<4)return 0;let sum=0;for(let i=0;i<ring.length-1;i++){const a=ring[i],b=ring[i+1];sum+=rad(b[0]-a[0])*(2+Math.sin(rad(a[1]))+Math.sin(rad(b[1])))}return Math.abs(sum*R*R/2)}
function polygonArea(rings){return Math.max(0,ringArea(rings[0]||[])-rings.slice(1).reduce((n,r)=>n+ringArea(r),0))}
function fmtLength(m){return m<1000?`${m.toLocaleString(undefined,{maximumFractionDigits:1})} m`:`${(m/1000).toLocaleString(undefined,{maximumFractionDigits:2})} km`}
function fmtArea(a){return `${a.toLocaleString(undefined,{maximumFractionDigits:a<10?2:1})} m²`}
function midpoint(a,b){return [(a[0]+b[0])/2,(a[1]+b[1])/2]}
function centroid(ring){const pts=ring.slice(0,-1);if(!pts.length)return ring[0]||[0,0];return [pts.reduce((s,p)=>s+p[0],0)/pts.length,pts.reduce((s,p)=>s+p[1],0)/pts.length]}
function marker(coords,content,klass=''){if(state.markers.length>=800)return;if(!Number.isFinite(coords[0])||!Number.isFinite(coords[1]))return;const el=document.createElement('div');el.className='measure-label '+klass;el.textContent=content;const m=new maplibregl.Marker({element:el,anchor:'center'}).setLngLat(coords).addTo(state.map);state.markers.push(m)}
function labelLine(points,close=false){const seq=close?points:points;for(let i=1;i<seq.length;i++){const a=seq[i-1],b=seq[i];if(distance(a,b)>.1)marker(midpoint(a,b),fmtLength(distance(a,b)),'segment')}}
function renderLabels(){state.markers.forEach(m=>m.remove());state.markers=[];if(!state.map||!state.map.getSource('features'))return;const showLengths=$('label-length').checked,showAreas=$('label-area').checked;if(!showLengths&&!showAreas)return;for(const item of visible()){const geom=item.feature.geometry;let lines=[],polys=[];if(geom.type==='LineString')lines=[geom.coordinates];if(geom.type==='MultiLineString')lines=geom.coordinates;if(geom.type==='Polygon')polys=[geom.coordinates];if(geom.type==='MultiPolygon')polys=geom.coordinates;if(showLengths){for(const line of lines)labelLine(line);for(const polygon of polys){const outer=polygon[0]||[];labelLine(outer);if(outer.length>1)marker(outer[0],`Perimeter ${fmtLength(lineLength(outer))}`)}}if(showAreas)for(const poly of polys)marker(centroid(poly[0]||[]),fmtArea(polygonArea(poly)),'area')}}
function setMode(mode){if(mode==='finish'){finishDraw();return}if(mode==='undo'){state.vertices.pop();updateDrawing();return}if(state.vertices.length)cancelDraw();state.mode=mode;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(state.map){state.map.getCanvas().style.cursor=mode==='select'?'': 'crosshair';state.map.doubleClickZoom[mode==='select'?'enable':'disable']()} const msg={select:'Click a feature to select it',point:'Click on the map to place points',line:'Click to add vertices · double-click to finish',polygon:'Click to add vertices · double-click to finish'};$('draw-hint').textContent=msg[mode];$('map-status').textContent=mode==='select'?'Ready':`Drawing ${mode}`}
function cancelDraw(){state.vertices=[];state.cursor=null;updateDrawing()}
function updateDrawing(){if(!state.map?.getSource('drawing'))return;const pts=state.vertices;const moving=state.cursor&&pts.length?[...pts,state.cursor]:pts;const fs=pts.map(p=>({type:'Feature',geometry:{type:'Point',coordinates:p},properties:{}}));if(moving.length>=2)fs.push({type:'Feature',geometry:{type:'LineString',coordinates:state.mode==='polygon'&&moving.length>=3?[...moving,moving[0]]:moving},properties:{}});if(state.mode==='polygon'&&moving.length>=3)fs.push({type:'Feature',geometry:{type:'Polygon',coordinates:[[...moving,moving[0]]]},properties:{}});state.map.getSource('drawing').setData({type:'FeatureCollection',features:fs});$('draw-hint').textContent=pts.length?`${pts.length} vertices · double-click or Finish to complete`:'Click on the map to place your first vertex'}
function finishDraw(){let pts=[...state.vertices];if(state.mode==='line'&&pts.length>=2){addFeatures([{type:'Feature',geometry:{type:'LineString',coordinates:pts},properties:{name:`Drawn polyline ${state.nextId}`}}],'Drawing');toast('Polyline added')}else if(state.mode==='polygon'&&pts.length>=3){pts.push([...pts[0]]);addFeatures([{type:'Feature',geometry:{type:'Polygon',coordinates:[pts]},properties:{name:`Drawn polygon ${state.nextId}`}}],'Drawing');toast('Polygon added')}else if(state.mode!=='select'){toast(`Need ${state.mode==='polygon'?3:2} vertices to finish`);return}cancelDraw();if(state.mode!=='select')setMode('select')}
function addVertex(coords){if(state.vertices.length&&distance(state.vertices.at(-1),coords)<.02)return;state.vertices.push(coords);updateDrawing()}
function setupMap(){if(!window.maplibregl){$('map-status').textContent='MapLibre could not load. Connect to the internet and reopen.';notice('MapLibre did not load. An internet connection is needed for the map library.');return}state.map=new maplibregl.Map({container:'map',style,center:[138.6007,-34.9285],zoom:13.2,attributionControl:false});state.map.addControl(new maplibregl.NavigationControl({showCompass:true}),'top-right');state.map.addControl(new maplibregl.ScaleControl({maxWidth:120,unit:'metric'}),'bottom-right');state.map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-left');state.map.on('load',()=>{refresh();updateDrawing()});state.map.on('mousemove',e=>{$('coords').textContent=`${e.lngLat.lng.toFixed(5)}, ${e.lngLat.lat.toFixed(5)}`;if(state.vertices.length){state.cursor=[e.lngLat.lng,e.lngLat.lat];updateDrawing()}});state.map.on('click',e=>{if(state.mode!=='select'){if(state.mode==='point'){const xy=[e.lngLat.lng,e.lngLat.lat];addFeatures([{type:'Feature',geometry:{type:'Point',coordinates:xy},properties:{name:`Drawn point ${state.nextId}`}}],'Drawing');return}addVertex([e.lngLat.lng,e.lngLat.lat]);return}const hits=state.map.queryRenderedFeatures(e.point,{layers:['points','lines','polygon-outline','polygons']});if(hits.length){state.selected=Number(hits[0].properties._fid);refresh()}else if(state.selected!==null){state.selected=null;refresh()}});state.map.on('dblclick',e=>{if(['line','polygon'].includes(state.mode)){e.preventDefault();finishDraw()}});state.map.on('error',e=>{if(e.error?.message&&state.metroReady)console.warn('Map tile error:',e.error.message)})}
function geoJSONtoFeatures(obj){if(obj.type==='FeatureCollection')return obj.features||[];if(obj.type==='Feature')return [obj];if(obj.type&&obj.coordinates||obj.type==='GeometryCollection')return[{type:'Feature',geometry:obj,properties:{}}];throw Error('Not a valid GeoJSON FeatureCollection, Feature or Geometry')}
function localChildren(node,name){return [...node.childNodes].filter(n=>n.nodeType===1&&n.localName===name)}
function childrenDeep(node,name){return [...node.getElementsByTagName('*')].filter(n=>n.localName===name)}
function localText(node,name){return localChildren(node,name)[0]?.textContent?.trim()||''}
function parseCoordinates(s){return (s||'').trim().split(/\s+/).filter(Boolean).map(t=>t.split(',').map(Number)).filter(p=>p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1]))}
function kmlGeom(el){switch(el.localName){case 'Point':{const c=parseCoordinates(childrenDeep(el,'coordinates')[0]?.textContent)[0];return c?{type:'Point',coordinates:c}:null}case 'LineString':case 'LinearRing':{const cs=parseCoordinates(childrenDeep(el,'coordinates')[0]?.textContent);return cs.length>=2?{type:'LineString',coordinates:cs}:null}case 'Polygon':{const outer=localChildren(el,'outerBoundaryIs')[0],inner=localChildren(el,'innerBoundaryIs');const rings=[outer,...inner].filter(Boolean).map(b=>parseCoordinates(childrenDeep(b,'coordinates')[0]?.textContent)).filter(r=>r.length>=3).map(r=>{if(distance(r[0],r.at(-1))>.01)r.push([...r[0]]);return r});return rings.length?{type:'Polygon',coordinates:rings}:null}case 'MultiGeometry':{const parts=localChildren(el,'Point').concat(localChildren(el,'LineString'),localChildren(el,'Polygon'),localChildren(el,'MultiGeometry')).flatMap(ch=>{const g=kmlGeom(ch);return !g?[]:g.type==='GeometryCollection'?g.geometries:[g]});return{type:'GeometryCollection',geometries:parts}}default:return null}}
function parseKML(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw Error('Invalid KML/XML document');const out=[];for(const pm of childrenDeep(doc,'Placemark')){const properties={};for(const field of ['name','description']){const t=localText(pm,field);if(t)properties[field]=t}for(const data of childrenDeep(pm,'Data')){const key=data.getAttribute('name');if(key)properties[key]=localText(data,'value')}for(const simple of childrenDeep(pm,'SimpleData')){const key=simple.getAttribute('name');if(key)properties[key]=simple.textContent?.trim()||''}for(const child of [...pm.childNodes].filter(n=>n.nodeType===1)){if(!['Point','LineString','Polygon','MultiGeometry'].includes(child.localName))continue;const geometry=kmlGeom(child);if(geometry)out.push({type:'Feature',geometry,properties})}}return out}
async function importFile(file){const name=file.name||'Imported';const lower=name.toLowerCase();let features;if(lower.endsWith('.kmz')){const zip=await JSZip.loadAsync(file);const entries=Object.values(zip.files).filter(f=>!f.dir&&f.name.toLowerCase().endsWith('.kml'));if(!entries.length)throw Error('KMZ contains no KML files');entries.sort((a,b)=>(a.name.toLowerCase()==='doc.kml'?-1:0)-(b.name.toLowerCase()==='doc.kml'?-1:0));features=parseKML(await entries[0].async('string'))}else if(lower.endsWith('.kml'))features=parseKML(await file.text());else if(lower.endsWith('.geojson')||lower.endsWith('.json'))features=geoJSONtoFeatures(JSON.parse(await file.text()));else throw Error('Unsupported file format');const count=addFeatures(features,name);if(!count)throw Error('No supported point, line or polygon geometry found');toast(`Imported ${count} feature${count===1?'':'s'} from ${name}`);fitFeatures(state.items.slice(-count))}
async function importFiles(files){for(const f of files){try{await importFile(f)}catch(e){toast(`${f.name}: ${e.message}`);console.error(e)}}$('file-input').value=''}
function kmlCoords(c){return c.map(x=>x.join(',')).join(' ')}
function geometryKML(g){switch(g.type){case 'Point':return `<Point><coordinates>${g.coordinates.join(',')}</coordinates></Point>`;case 'MultiPoint':return `<MultiGeometry>${g.coordinates.map(c=>geometryKML({type:'Point',coordinates:c})).join('')}</MultiGeometry>`;case 'LineString':return `<LineString><tessellate>1</tessellate><coordinates>${kmlCoords(g.coordinates)}</coordinates></LineString>`;case 'MultiLineString':return `<MultiGeometry>${g.coordinates.map(c=>geometryKML({type:'LineString',coordinates:c})).join('')}</MultiGeometry>`;case 'Polygon':return `<Polygon><tessellate>1</tessellate>${g.coordinates.map((ring,i)=>`<${i?'innerBoundaryIs':'outerBoundaryIs'}><LinearRing><coordinates>${kmlCoords(ring)}</coordinates></LinearRing></${i?'innerBoundaryIs':'outerBoundaryIs'}>`).join('')}</Polygon>`;case 'MultiPolygon':return `<MultiGeometry>${g.coordinates.map(c=>geometryKML({type:'Polygon',coordinates:c})).join('')}</MultiGeometry>`;case 'GeometryCollection':return `<MultiGeometry>${g.geometries.map(geometryKML).join('')}</MultiGeometry>`;default:return ''}}
function makeKML(features){return `<?xml version="1.0" encoding="UTF-8"?>\n<kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>GeoForge Export</name>${features.map(f=>{const p=f.properties||{};const name=p.name||'Untitled';const desc=p.description?`<description>${escapeXML(p.description)}</description>`:'';const extra=Object.entries(p).filter(([k])=>!['name','description'].includes(k)).map(([k,v])=>`<Data name="${escapeXML(k)}"><value>${escapeXML(typeof v==='object'?JSON.stringify(v):v)}</value></Data>`).join('');return `<Placemark><name>${escapeXML(name)}</name>${desc}${extra?`<ExtendedData>${extra}</ExtendedData>`:''}${geometryKML(f.geometry)}</Placemark>`}).join('')}</Document></kml>`}
function save(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000)}
async function exportAs(fmt){const features=scoped();if(!features.length){toast('Nothing to export in the selected scope');return}const name=($('export-name').value.trim()||'geoforge-export').replace(/\.(geojson|json|kml|kmz)$/i,'').replace(/[\\/:*?"<>|]/g,'-');if(fmt==='geojson')save(new Blob([JSON.stringify({type:'FeatureCollection',features},null,2)],{type:'application/geo+json'}),name+'.geojson');else{const xml=makeKML(features);if(fmt==='kml')save(new Blob([xml],{type:'application/vnd.google-earth.kml+xml'}),name+'.kml');else{const zip=new JSZip();zip.file('doc.kml',xml);save(await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),name+'.kmz')}}toast(`Exported ${features.length} feature${features.length===1?'':'s'} to ${fmt.toUpperCase()}`)}
function xmlElements(root,name){return [...root.getElementsByTagName('*')].filter(n=>n.localName===name)}
function xmlChild(root,name){return [...root.children].find(n=>n.localName===name)}
function parseCapabilities(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror')||xmlElements(doc,'ExceptionReport').length)throw Error('MetroMap returned an invalid capabilities response');const layers=xmlElements(doc,'Layer');const layer=layers.find(l=>xmlChild(l,'Identifier')?.textContent==='Australia_latest')||layers.find(l=>xmlChild(l,'Identifier')?.textContent==='Australian_capital_cities_latest')||layers[0];if(!layer)throw Error('No WMTS image layers in capabilities');const layerName=xmlChild(layer,'Identifier')?.textContent?.trim();const format=xmlElements(layer,'Format').map(x=>x.textContent.trim()).find(f=>/image\/(png|jpeg|jpg|webp)/i.test(f))||'image/png';const matrixLinks=xmlElements(layer,'TileMatrixSetLink').map(l=>xmlChild(l,'TileMatrixSet')?.textContent?.trim()).filter(Boolean);const matrixSets=xmlElements(doc,'TileMatrixSet').filter(el=>xmlChild(el,'Identifier'));
const matching=matrixSets.filter(s=>{const ident=xmlChild(s,'Identifier')?.textContent?.trim();const crs=xmlChild(s,'SupportedCRS')?.textContent?.trim()||'';return matrixLinks.includes(ident)&&(/3857|900913|webmercator|GoogleMapsCompatible/i.test(crs+' '+ident))});if(!matching.length)throw Error('This WMTS service does not advertise an EPSG:3857 tile matrix set compatible with MapLibre');matching.sort((a,b)=>/webmercator/i.test(xmlChild(a,'Identifier')?.textContent||'')?-1:/webmercator/i.test(xmlChild(b,'Identifier')?.textContent||'')?1:0);const matrix=matching[0],matrixId=xmlChild(matrix,'Identifier').textContent.trim();const ids=xmlElements(matrix,'TileMatrix').map(m=>xmlChild(m,'Identifier')?.textContent?.trim()).filter(Boolean);const suffixes=ids.map(x=>x.match(/^(.*?)(\d+)$/)).filter(Boolean);let prefix='';if(suffixes.length&&suffixes.every(m=>m[1]===suffixes[0][1]&&Number(m[2])>=0))prefix=suffixes[0][1];if(ids.some(x=>!new RegExp('^'+prefix.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\d+$').test(x)))throw Error('Unsupported WMTS tile matrix identifiers');const maxzoom=ids.length?Math.max(...suffixes.map(m=>Number(m[2]))):21;
return{layerName,format,matrixId,prefix,maxzoom:Math.min(maxzoom,23)}}
function metroEndpoint(key){return `https://api.metromap.com.au/ogc/gda2020/key/${encodeURIComponent(key)}/state:LATEST/service`}
function metroTiles(key,config){const url=metroEndpoint(key);const p=[['SERVICE','WMTS'],['REQUEST','GetTile'],['VERSION','1.0.0'],['LAYER',config.layerName],['STYLE','default'],['FORMAT',config.format],['TILEMATRIXSET',config.matrixId],['TILEMATRIX',config.prefix+'{z}'],['TILEROW','{y}'],['TILECOL','{x}']];return url+'?'+p.map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v).replace(/%7B/gi,'{').replace(/%7D/gi,'}')).join('&')}
function setBase(kind){if(!state.map)return;if(kind==='metromap'&&!state.metroReady){toast('Enter an API key and connect MetroMap first');$('api-key').focus();return}state.map.setLayoutProperty('osm','visibility',kind==='osm'?'visible':'none');if(state.map.getLayer('metro'))state.map.setLayoutProperty('metro','visibility',kind==='metromap'?'visible':'none');document.querySelectorAll('.base-option').forEach(el=>el.classList.toggle('selected',el.dataset.base===kind));$('basemap-caption').textContent=kind==='osm'?'OpenStreetMap':'MetroMap · GDA2020 WMTS';$('map-status').textContent=kind==='osm'?'OpenStreetMap active':'MetroMap active'}
function connection(message,kind){$('connection-state').className='connection-state '+(kind||'');$('connection-state').lastElementChild.textContent=message}
async function connectMetro(){const key=$('api-key').value.trim();if(!state.map){toast('MapLibre has not loaded. Check your internet connection');return}if(!key){toast('Enter your MetroMap API key');return}if($('remember-key').checked)localStorage.setItem('geoforge-metromap-key',key);else localStorage.removeItem('geoforge-metromap-key');$('connect-metro').disabled=true;connection('Checking WMTS capabilities…','');try{const response=await fetch(metroEndpoint(key)+'?REQUEST=GetCapabilities&SERVICE=WMTS',{cache:'no-store'});if(!response.ok)throw Error(`WMTS returned HTTP ${response.status}`);const conf=parseCapabilities(await response.text());const template=metroTiles(key,conf);if(state.map.getLayer('metro'))state.map.removeLayer('metro');if(state.map.getSource('metro'))state.map.removeSource('metro');state.map.addSource('metro',{type:'raster',tiles:[template],tileSize:256,maxzoom:conf.maxzoom,attribution:'© MetroMap'});state.map.addLayer({id:'metro',type:'raster',source:'metro',layout:{visibility:'none'}},'polygons');state.metroReady=true;state.metroTemplate=template;setBase('metromap');connection(`Connected · ${conf.layerName} · ${conf.matrixId}`,'connected');toast('MetroMap WMTS connected')}catch(e){connection('Connection failed: '+e.message,'error');notice('MetroMap: '+e.message+'. Check WMTS access, key, and cross-origin permissions.');console.error('MetroMap connection:',e)}finally{$('connect-metro').disabled=false}}
function setupDrag(){const bar=$('drawbar'),handle=$('drag-handle');let start=null;handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();const rect=bar.getBoundingClientRect(),parent=$('map').getBoundingClientRect();bar.style.transform='none';bar.style.left=(rect.left-parent.left)+'px';bar.style.top=(rect.top-parent.top)+'px';start={x:e.clientX,y:e.clientY,left:parseFloat(bar.style.left),top:parseFloat(bar.style.top)};handle.setPointerCapture(e.pointerId)});handle.addEventListener('pointermove',e=>{if(!start)return;const bounds=$('map').getBoundingClientRect();bar.style.left=Math.max(0,Math.min(bounds.width-bar.offsetWidth,start.left+e.clientX-start.x))+'px';bar.style.top=Math.max(0,Math.min(bounds.height-bar.offsetHeight,start.top+e.clientY-start.y))+'px'});handle.addEventListener('pointerup',()=>start=null);handle.addEventListener('pointercancel',()=>start=null)}
function setupEvents(){const dz=$('dropzone');dz.onclick=()=>$('file-input').click();dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('file-input').click()}};dz.ondragover=e=>{e.preventDefault();dz.classList.add('over')};dz.ondragleave=()=>dz.classList.remove('over');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('over');importFiles([...e.dataTransfer.files])};$('file-input').onchange=e=>importFiles([...e.target.files]);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('label-length').onchange=renderLabels;$('label-area').onchange=renderLabels;$('zoom-all').onclick=()=>fitFeatures();$('delete-selected').onclick=()=>{state.items=state.items.filter(x=>x.id!==state.selected);state.selected=null;refresh();toast('Feature deleted')};$('clear-btn').onclick=()=>{if(!state.items.length)return;if(!confirm(`Remove all ${state.items.length} features from the workspace?`))return;state.items=[];state.selected=null;cancelDraw();refresh();toast('Workspace cleared')};for(const fmt of ['geojson','kml','kmz'])$('export-'+fmt).onclick=()=>exportAs(fmt).catch(e=>toast('Export failed: '+e.message));document.querySelectorAll('.base-option').forEach(b=>b.onclick=()=>setBase(b.dataset.base));$('connect-metro').onclick=connectMetro;$('show-key').onclick=()=>{$('api-key').type=$('api-key').type==='password'?'text':'password'};$('remember-key').onchange=()=>{if(!$('remember-key').checked)localStorage.removeItem('geoforge-metromap-key');else if($('api-key').value.trim())localStorage.setItem('geoforge-metromap-key',$('api-key').value.trim())};$('forget-key').onclick=()=>{localStorage.removeItem('geoforge-metromap-key');$('remember-key').checked=false;$('api-key').value='';toast('Saved MetroMap key removed')};$('help-btn').onclick=()=>$('help-modal').classList.remove('hidden');$('close-help').onclick=$('got-it').onclick=()=>$('help-modal').classList.add('hidden');$('help-modal').onclick=e=>{if(e.target.id==='help-modal')$('help-modal').classList.add('hidden')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('help-modal').classList.contains('hidden'))$('help-modal').classList.add('hidden');else if(state.vertices.length)cancelDraw();else if(state.mode!=='select')setMode('select')}if((e.key==='Backspace'||e.key==='Delete')&&state.vertices.length&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();state.vertices.pop();updateDrawing()}});$('settings-panel')?.addEventListener('click',()=>{});document.querySelector('.settings-panel').addEventListener('click',e=>{if(innerWidth<=1120&&e.offsetX<12)e.currentTarget.classList.toggle('expanded')});document.querySelector('.sidebar').addEventListener('click',e=>{if(innerWidth<=700&&e.offsetX>e.currentTarget.clientWidth-15)e.currentTarget.classList.toggle('expanded')});const saved=localStorage.getItem('geoforge-metromap-key');if(saved){$('api-key').value=saved;$('remember-key').checked=true}setupDrag()}
setupEvents();setupMap();
})();
