// Overtime-owned staff pool and work-pattern editors. No allocation algorithm.
(function () {
  'use strict';
  var clone = function (v) { return JSON.parse(JSON.stringify(v)); };
  var esc = function (v) { return window.HortOpsSecurityUtils.escapeHtml(String(v == null ? '' : v)); };
  var attr = function (v) { return window.HortOpsSecurityUtils.escapeHtmlAttr(String(v == null ? '' : v)); };
  var state = function () { return window.HortOpsApp.state; };
  var baseline = function () { return JSON.stringify({tags:state().poolTags || [], roster:state().staffList || [], jobs:state().jobs || [], assignments:state().customAssignments || {}, rostering:state().rostering || {}}); };
  var panel = 'background:#f0fdf4;border:1px solid #a7f3d0;border-radius:8px;padding:12px;';
  function tagChecks(tags, selected, attribute) {
    return tags.map(function (t) { return '<label style="display:inline-flex;align-items:center;gap:6px;margin:5px"><input type="checkbox" '+attribute+'="'+attr(t.id)+'" '+(selected.indexOf(t.id)>=0?'checked':'')+' '+(!t.active && selected.indexOf(t.id)<0?'disabled':'')+'>#'+esc(t.label)+(t.active?'':' (retired)')+'</label>'; }).join('') || '<p>No pools yet. Create pools in Workforce Registry.</p>';
  }
  window.HortOpsStaffPoolModal = {
    model:null,
    open:function (staffId) {
      this.model={staffId:staffId || null, tags:clone(state().poolTags || []), roster:clone(state().staffList || []), base:baseline(), error:''};
      if (window.HortOpsModalUtils) window.HortOpsModalUtils.lockBackgroundScroll();
      this.render();
    },
    close:function () { this.model=null; var root=document.getElementById('pool-modal-root'); if(root)root.innerHTML=''; if(window.HortOpsModalUtils)window.HortOpsModalUtils.unlockBackgroundScroll(); },
    createTag:function (label) {
      if(!this.model)return;
      label=String(label || '').trim().replace(/^#/,'');
      if(!/^[A-Za-z][A-Za-z0-9_-]{0,39}$/.test(label) || this.model.tags.some(function(t){return t.label.toLowerCase()===label.toLowerCase();})) {this.model.error='Use a unique tag: a letter followed by up to 39 letters, digits, underscores or hyphens.';this.render();return;}
      var id='POOL-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9);
      this.model.tags.push({id:id,label:label,active:true,history:[{at:new Date().toISOString(),action:'created'}]}); this.model.error=''; this.render();
    },
    setTagActive:function(id,active){ if(!this.model)return;var t=this.model.tags.find(function(t){return t.id===id;});if(!t)return;t.history=t.history || [];t.history.push({at:new Date().toISOString(),action:active?'reactivated':'retired',before:t.active,after:active});t.active=active;this.render(); },
    setMembership:function(id,checked){if(!this.model)return;var s=this.model.roster.find(function(s){return s.id===this.model.staffId;},this);if(!s)return;var ids=s.poolTagIds || [];s.poolTagIds=checked?Array.from(new Set(ids.concat(id))):ids.filter(function(v){return v!==id;});this.render();},
    save:function(){
      if(!this.model)return;
      if(baseline()!==this.model.base){this.model.error='Workspace changed while this editor was open. Cancel and reopen to review current values.';this.render();return;}
      var m=this.model, now=new Date().toISOString();
      m.roster.forEach(function(s){var before=(state().staffList || []).find(function(v){return v.id===s.id;});var old=before && before.poolTagIds || [];if(JSON.stringify(old)!==JSON.stringify(s.poolTagIds || [])){s.poolTagHistory=clone(before.poolTagHistory || []);s.poolTagHistory.push({at:now,before:old.slice(),after:(s.poolTagIds || []).slice()});}});
      var result=window.HortOpsApp._commitCanonicalProposal({poolTags:m.tags,roster:m.roster});
      if(!result || result.success===false){m.error=result && result.error || 'Could not save pool changes.';this.render();return;}
      this.close();window.HortOpsApp.recomputeDigest();window.HortOpsApp.renderCurrentView();
    },
    render:function(){
      if(!this.model)return;var m=this.model, root=document.getElementById('pool-modal-root');if(!root)return;
      var staff=m.roster.find(function(s){return s.id===m.staffId;});
      var changed=m.tags.filter(function(t){var before=(state().poolTags || []).find(function(b){return b.id===t.id;});return !before || before.active!==t.active;}).map(function(t){return t.id;});
      if(staff){var previous=((state().staffList || []).find(function(s){return s.id===staff.id;}) || {}).poolTagIds || [], next=staff.poolTagIds || [];changed=changed.concat(previous.filter(function(id){return next.indexOf(id)<0;}),next.filter(function(id){return previous.indexOf(id)<0;}));}
      var jobs=(state().jobs || []).filter(function(j){return (j.preferredPoolTagIds || []).concat(j.exclusivePoolTagIds || []).some(function(id){return changed.indexOf(id)>=0;});});
      var today=window.HortOpsDateUtils.getLocalDateKey(), affectedIds=jobs.map(function(j){return j.id;});
      var future=(state().allShifts || []).filter(function(s){return s.date>=today && affectedIds.indexOf(s.jobId)>=0 && (s.assignedStaffIds || []).length;});
      var impacts='<div style="'+panel+'"><strong>Assignment impact review</strong><p>'+jobs.length+' job definitions reference the affected pools'+(jobs.length?': '+jobs.map(function(j){return esc(j.name);}).join(', '):'.')+'</p><p>'+future.length+' currently staffed future occurrences may need review. Existing assignments are retained. Future staffing is checked against active pool membership; review affected jobs before saving.</p></div>';
      root.innerHTML='<div class="modal-overlay"><div class="modal-card modal-lg"><div class="modal-header"><h2>'+ (staff?'Staff pools: '+esc(staff.name):'Manage workforce pools')+'</h2><button type="button" class="btn btn-secondary" data-pool-close>Close</button></div><div class="modal-body" style="background:#f8fafc">'+(m.error?'<p role="alert" style="color:#991b1b">'+esc(m.error)+'</p>':'')+(staff?'<section style="'+panel+'"><h3>Cross-team memberships</h3>'+tagChecks(m.tags,staff.poolTagIds || [],'data-membership')+'</section>':'')+'<section style="margin-top:12px"><h3>Pool catalogue</h3><div style="display:flex;gap:8px"><input class="form-input" id="pool-new-label" aria-label="New pool tag" placeholder="ParkRanger" maxlength="40"><button type="button" class="btn btn-secondary" data-pool-create>Create tag</button></div>'+m.tags.map(function(t){return '<div style="display:flex;justify-content:space-between;margin-top:8px"><strong>#'+esc(t.label)+(t.active?'':' (retired)')+'</strong><button type="button" class="btn btn-secondary" data-pool-active="'+attr(t.id)+'">'+(t.active?'Retire':'Reactivate')+'</button></div>';}).join('')+'</section>'+impacts+'</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-pool-close>Cancel</button><button type="button" class="btn btn-primary" data-pool-save>Save pools</button></div></div></div>';
      root.onclick=function(e){var b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-pool-close'))window.HortOpsStaffPoolModal.close();if(b.hasAttribute('data-pool-create'))window.HortOpsStaffPoolModal.createTag(document.getElementById('pool-new-label').value);if(b.hasAttribute('data-pool-save'))window.HortOpsStaffPoolModal.save();if(b.hasAttribute('data-pool-active')){var id=b.getAttribute('data-pool-active'),t=m.tags.find(function(t){return t.id===id;});window.HortOpsStaffPoolModal.setTagActive(id,!t.active);}};
      root.onchange=function(e){if(e.target.hasAttribute('data-membership'))window.HortOpsStaffPoolModal.setMembership(e.target.getAttribute('data-membership'),e.target.checked);};
    }
  };
  // Existing registry keeps its own filters, typography and actions.
  var registry=window.HortOpsStaffRegistry, oldRegistryRender=registry.render;
  registry.render=function(s){var html=oldRegistryRender.call(this,s);html=html.replace('<div class="panel-header">','<div class="panel-header"><button type="button" class="btn btn-secondary" onclick="window.HortOpsStaffPoolModal.open()">Manage pools</button>');
    (s.staffList || []).forEach(function(person){var safeId=attr(person.id), marker="window.HortOpsStaffQualificationModal.open('"+safeId+"')";var location=html.indexOf(marker);if(location<0)return;var start=html.lastIndexOf('<button',location);var encodedId=attr(JSON.stringify(person.id));var chips=(person.poolTagIds || []).map(function(id){var t=(s.poolTags || []).find(function(t){return t.id===id;});return t?'<span class="badge badge-emerald">#'+esc(t.label)+(t.active?'':' (retired)')+'</span>':'';}).join('');html=html.slice(0,start)+'<span style="display:flex;gap:4px;flex-wrap:wrap">'+chips+'</span><button type="button" class="btn btn-secondary" onclick="window.HortOpsStaffPoolModal.open('+encodedId+')">Pools</button>'+html.slice(start);});return html;};
  var job=window.HortOpsJobEditModal, recurrence=window.HortOpsJobEditRecurrenceForm, oldRecurrence=recurrence.render, oldRender=job.renderModal, oldExclusiveCheck=job.toggleExclusiveCheck;
  job.toggleExclusiveCheck=function(checked){if(!this.formData)return;this.formData.exclusivePoolSource=checked?'teams':'none';this.formData.isExclusive=false;return oldExclusiveCheck.call(this,checked);};
  function patternDefault(){return {mode:'weekly',startDate:new Date().getFullYear()+'-01-01',days:[6,0],runLength:1,includePublicHolidays:false,excludedDates:[]};}
  recurrence.render=function(ctx){var d=ctx.data;if(d.frequencyType!=='work_pattern')return oldRecurrence.call(this,ctx).replace('</select>','<option value="work_pattern">Multiple days / public holidays</option></select>');
    var p=d.workPattern || patternDefault();d.workPattern=p;
    var year=Number(p.startDate.slice(0,4)), dates=window.HortOpsPlanningRules.dates(d,year);
    return '<section style="'+panel+'"><label>Frequency Cadence<select class="form-select" data-planning-frequency><option value="recurring_weeks">Recurring Every N Weeks</option><option value="annual">Annual Shift</option><option value="one_off">One-off Shift</option><option value="work_pattern" selected>Multiple days / public holidays</option></select></label><label>Pattern<select class="form-select" data-pattern="mode"><option value="weekly" '+(p.mode==='weekly'?'selected':'')+'>Weekly weekdays plus public holidays</option><option value="run" '+(p.mode==='run'?'selected':'')+'>One-off consecutive run (1–4 days)</option></select></label><div style="display:flex;gap:12px"><label>Start date<input type="date" class="form-input" data-pattern="startDate" value="'+attr(p.startDate)+'"></label>'+(p.mode==='weekly'?'<label>End date (optional)<input type="date" class="form-input" data-pattern="endDate" value="'+attr(p.endDate || '')+'"></label>':'<label>Consecutive days<input type="number" min="1" max="4" class="form-input" data-pattern="runLength" value="'+p.runLength+'"></label>')+'</div>'+(p.mode==='weekly'?'<fieldset><legend>Recurring weekdays (up to four consecutive days)</legend>'+['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(function(n,i){return '<label style="margin:5px"><input type="checkbox" data-pattern-day="'+i+'" '+(p.days.indexOf(i)>=0?'checked':'')+'>'+n+'</label>';}).join('')+'</fieldset><label><input type="checkbox" data-pattern="includePublicHolidays" '+(p.includePublicHolidays?'checked':'')+'>Include full-day South Australian public holidays</label>':'')+'<label style="display:block">Excluded dates (one YYYY-MM-DD per line)<textarea class="form-input" data-pattern="excludedDates" rows="3">'+esc(p.excludedDates.join('\n'))+'</textarea></label><p>Overlapping weekday and holiday rules create one occurrence per date. Staffing is independent for each daily occurrence.</p><details><summary>'+dates.length+' occurrences in '+year+' — preview exact dates</summary><p>'+dates.map(esc).join(' · ')+'</p></details></section>';
  };
  job.setPlanningField=function(field,value){if(!this.formData)return;if(field==='frequencyType'){this.formData.frequencyType=value;if(value==='work_pattern'&&!this.formData.workPattern)this.formData.workPattern=patternDefault();}else{var p=this.formData.workPattern || patternDefault();if(field==='endDate'&&!value)delete p.endDate;else p[field]=value;if(p.mode==='run')p.includePublicHolidays=false;this.formData.workPattern=p;}this.renderModal();};
  job.togglePatternDay=function(day,checked){if(!this.formData)return;var p=this.formData.workPattern;p.days=checked?Array.from(new Set(p.days.concat(day))):p.days.filter(function(d){return d!==day;});this.renderModal();};
  job.setPoolSource=function(value){if(!this.formData)return;this.formData.exclusivePoolSource=value;this.formData.isExclusiveTeams=value==='teams';this.formData.isExclusive=false;if(value==='teams'&&!(this.formData.exclusiveTeams || []).length){var primary=this.formData.primaryTeam || this.formData.defaultTeam;this.formData.exclusiveTeams=primary?[primary]:[];}this.renderModal();};
  job.togglePoolTag=function(field,id,checked){if(!this.formData)return;var a=this.formData[field] || [];this.formData[field]=checked?Array.from(new Set(a.concat(id))):a.filter(function(v){return v!==id;});this.renderModal();};
  job.renderModal=function(){if(this._planningRendering)return;this._planningRendering=true;try{oldRender.call(this);if(!this.formData)return;var root=document.getElementById('job-edit-modal-root'),body=root && root.querySelector('.modal-body');if(!body)return;var d=this.formData,source=window.HortOpsPlanningRules.source(d), section=document.createElement('section');section.style.cssText=panel;
    section.innerHTML='<h3>Cross-team staff pools</h3><p>Tags select pools, not qualifications. Preferred tagged candidates rank first; all safety and eligibility checks still apply.</p><strong>Preferred pools (any selected tag)</strong><div>'+tagChecks(state().poolTags || [],d.preferredPoolTagIds || [],'data-preferred-pool')+'</div><label>Exclusive pool source<select class="form-select" data-pool-source><option value="none" '+(source==='none'?'selected':'')+'>Unrestricted</option><option value="teams" '+(source==='teams'?'selected':'')+'>Existing team restrictions</option><option value="tags" '+(source==='tags'?'selected':'')+'>Tagged staff only</option></select></label>'+(source==='tags'?'<strong>Exclusive pools (any selected tag)</strong><div>'+tagChecks(state().poolTags || [],d.exclusivePoolTagIds || [],'data-exclusive-pool')+'</div><p>An empty exclusive pool cannot be filled automatically or manually.</p>':'');body.insertBefore(section,body.children[2] || null);
    root.onchange=function(e){if(job._planningRendering)return;var t=e.target;if(t.hasAttribute('data-planning-frequency'))job.setPlanningField('frequencyType',t.value);if(t.hasAttribute('data-pattern')){var f=t.getAttribute('data-pattern'),v=t.value;if(f==='includePublicHolidays')v=t.checked;if(f==='runLength')v=Number(v);if(f==='excludedDates')v=v.split(/[\s,]+/).filter(Boolean);job.setPlanningField(f,v);}if(t.hasAttribute('data-pattern-day'))job.togglePatternDay(Number(t.getAttribute('data-pattern-day')),t.checked);if(t.hasAttribute('data-pool-source'))job.setPoolSource(t.value);if(t.hasAttribute('data-preferred-pool'))job.togglePoolTag('preferredPoolTagIds',t.getAttribute('data-preferred-pool'),t.checked);if(t.hasAttribute('data-exclusive-pool'))job.togglePoolTag('exclusivePoolTagIds',t.getAttribute('data-exclusive-pool'),t.checked);};
    }finally{this._planningRendering=false;}
  };
})();
